// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djpvakobbvnavfyvibah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqcHZha29iYnZuYXZmeXZpYmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzUyMTUsImV4cCI6MjA1OTc1MTIxNX0.vKNtanC_3aFO3LQdxdijX_jUYg5ruT688WzP706wTug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);